# Generated by Django 2.1.4 on 2019-06-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humankapital', '0003_auto_20190609_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unfortunateevent',
            name='event_ptr',
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='humankapital.Person'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='sold',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='UnfortunateEvent',
        ),
    ]
