# Generated by Django 2.1.4 on 2019-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humankapital', '0004_auto_20190609_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='death',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='positive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='reason',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
