# Generated by Django 2.1.4 on 2019-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humankapital', '0007_auto_20190609_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
