# Generated by Django 2.1.4 on 2019-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humankapital', '0008_person_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='percent',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
